[tool.isort]
multi_line_output = 3
include_trailing_comma = true
skip = [".gitingore", "__init__.py"]
known_first_party = ["benchmarks, "torch_geometric"]

[tool.flake8]
ignore = ["F811", "W503", "W504"]
